NAME : SUMEDH KALE
MIS  : 111403062

CRIC ADDICT (Cricket Scoreboard Software)

> ALWAYS MAKE THE TERMINAL FULL SCREEN BEFORE STARTING THE SOFTWARE.
> USE DEFAULT TERMINAL BACKGROUND COLORS FOR BEST VISUAL EXPERIENCE, i.e. ON TERMINAL GO TO EDIT > PROFILE PREFRENCES > COLORS > SELECT USE COLORS FROM SYSYTEM THEME OPTION
> THE SOFTWARE CONSISTS PLAYER PROFILES AND ACTUAL SCOREBOARD.
> IN PLAYER PROFILE, BATTING AND BOWLING PROFILE OF THE PLAYER CAN BE VIEWED.
> THE SOFTWARE DOES NOT ALLOW TO SELECT SAME TEAMS FOR A MATCH.
> IN TEAM SQAUD SELECTION, PLAYERS CAN BE SWAPPED ACCORDING TO SQUAD REQUIREMENT.
> TOSS GUIDELINES ARE PROVIDED ACCORDING TO PITCH TYPE AND WEATHER CONDITIONS SELECTED.
> VENUE FOR PLAYING A MATCH CAN BE SELECTED.
> THE RESULT OF THE TOSS AND THE CHOICE OF BATTING/BOWLING BY THE OPPONENT TEAM IS GENERATED RANDOMLY.
> ** PLEASE READ THE GUIDELINES ON SCOREBOARD SCREEN.
> THE BATSMAN ROTATE STRIKE AFTER TAKING A ONE RUN, AFTER TAKING THREE RUNS, AND AFTER END OF AN OVER.
> THE BATSMAN WHO IS ON STRIKE CAN BE IDENTIFIED BY '*' AT THE START OF ITS NAME.
> THE SOFTWARE ALLOWS FOUR TYPES OF DISSMISALS OF BATSMAN NAMELY CAUGHT AND BOWLED, CATCH OUT, BOWLED, AND RUNOUT.
> IN CASE OF RUNOUT, ALWAYS THE BATSMAN ON STRIKE IS OUT.
> THE BOWLER CAN BOWL A MAIDEN OVER.
> EXTRAS ARE IN FORM OF WIDES NO NOBALLS. 
> AFTER THE END OF INNINGS BATTING AND BOWLING SCORECARDS OF RESPECTIVE TEAMS, AND OVER BY OVER DETAILS ARE SHOWN.
   
